name: Lighthouse CI
on:
  push:
    branches: [ "master" ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install -g @lhci/cli@0.13.x
      - run: |
          lhci autorun \
            --collect.settings.url="https://connorm-55.github.io/cayman/" \
            --assert.assertions.performance="error=0,warning=90" \
            --assert.assertions.accessibility="error=0,warning=90" \
            --upload.target=temporary-public-storage
