name: Lighthouse CI

on:
  push:
    branches: [ "master" ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Install Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.13.x
      - name: Run Lighthouse CI on live site
        run: |
          lhci collect --url=https://connorm-55.github.io/cayman/ \
            --settings.onlyCategories=performance,accessibility \
            --settings.emulatedFormFactor=desktop
          lhci assert --assertions.performance=warning=90,error=0 \
                      --assertions.accessibility=warning=90,error=0
          lhci upload --target=temporary-public-storage
